### ISSUE TITLE
Starting the engine can take up a long time

### ISSUE THREAD

**Issue by ponsoc** [totaljs/flowstream#3] opened 2021-08-24 14:03 UTC
Hi Peter,

Starting the engine can take a long time. especially when you have a lot of components that share NPM packages.
From what we have investigated it seems like it is actually trying to install overlapping NPM packages again and again.

**Comment by petersirka** [comment] 2021-08-24 14:35
Hi @roelvanegmond.
Would you please check the version of the Total.js framework? We have improved `NPMINSTALL()` method in `v0.0.45`: https://github.com/totaljs/framework4/blob/master/changelog.txt#L41 

BTW: you can test our new stable beta version `$ npm install total4@beta`. Today I have added the `pause()` method to the FlowStream, and after release - I'll update the designer by adding a pause button. The `Stop` button is a bit complicated to implement because there is needed to destroy the entire FlowStream that may create more significant troubles in some cases. However, a pause state can solve a lot of things.

Let me know if the problem with NPM packages will persist in the beta version `0.0.46-5`.

**Comment by petersirka** [comment] 2021-08-24 14:37
However, I was assigned a bug label. I'm curious if the problem persists.

**Comment by alaminopu** [comment] 2021-08-26 00:55
Hi @petersirka, I can confirm that using the new version of `total4@beta` improved a lot.  Now it takes less loading time.  

Will try out the pause functionality, however, I believe it doesn't clear up the message (when pausing) and start processing the existing messages if we hit **play** again. 

`Stop` is very crucial feature specially when you start processing millions of messages but suddenly thought to stop the current flow. 

I was able to update the `flowstream` module with the following changes and make it stop, whenever a stop action is trigger in the `flowstreamdesigner`

```javascript
      case 'stop':
        const currentFlow = FLOWS[flow.id];
        // destroy the current flow
        currentFlow.destroy();
        break;
```

But then if I try to run the flow again by closing it and open it again or trying to use the `Apply` button, I receive the following error.

```bash
======= 2021-08-26 00:41:14: TypeError: Cannot read property 'flow' of null TypeError: Cannot read property 'flow' of null
    at Flow.FP.use (/Users/Opu/Office/Xillio/xill4/xill4-engine/node_modules/total4/flowstream.js:1023:17)
    at Object.MAKEFLOWSTREAM.flow.proxy.message (/Users/Opu/Office/Xillio/xill4/xill4-engine/modules/flowstream.js:1146:10)
    at MessagePort.<anonymous> (/Users/Opu/Office/Xillio/xill4/xill4-engine/modules/flowstream.js:586:17)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:353:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

Would it be possible to re-initialise a flow with existing components and connection?

**Comment by petersirka** [comment] 2021-08-30 10:45
Error is correct because you destroyed the entire FlowStream instance. The FlowStream designer reads data from the FlowStream instance directly (schema, components, stats, etc.). However, you killed the instance - therefore, that error.

I believe that `stop` is a significant feature, but it's impossible to add it right now. Only the way is to use the `pause` functionality (btw. you can rename it to `stop`).

**Comment by alaminopu** [comment] 2021-09-03 14:31
@roelvanegmond Does engine still take a long time for you? I guess with new changes it's not any more?  @petersirka  Shall we create an another github issue for the `stop` feature and close this one?

**Comment by petersirka** [comment] 2021-09-04 08:17
@alaminopu Yes, but I won't implement the `stop` feature because it's impossible to do.

**Comment by alaminopu** [comment] 2021-09-16 12:25
@petersirka  we end up tweaking pause functionality and made it work like `stop`.

**Closed as completed** 2021-09-16 12:28 UTC
Labels: bug
